[project]
name = "woosmap"
version = "0.1.0"
description = "Use Woosmap server to add location intelligence capabilities"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "debugpy>=1.8.19",
    "httpx>=0.28.1",
    "mcp[cli]>=1.25.0",
]
